<a href="https://colab.research.google.com/github/kraneelManandhar/ConceptsAndTechnologiesOfAI/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
a = np.array([1,2,3,4,5])
b = [10]
a+b

array([11, 12, 13, 14, 15])

In [17]:
a = np.array([1,2,3,4,5])
a.ndim

1

In [15]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
a.ndim

2

In [20]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
type(a)

numpy.ndarray

In [21]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
a.shape

(2, 5)

In [24]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
              [1,2,3,4,5]])
a.shape

(3, 5)

In [26]:
a = np.array([[1,2],
             [3,4]])
a.shape
type(a)

numpy.ndarray

In [31]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
c = np.arange(12).reshape(6,2)
c

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [33]:
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
k = np.eye(3)
k

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
b = np.array([[4,5,6,7,8],
              [4,5,6,7,8]])
a+b

array([[ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])